/**
 * This file was generated by Payload.
 * It is used to override the default React import map with a custom one.
 */

import type { ImportMap } from 'payload'

export const importMap: ImportMap = {
  "@payloadcms/ui#CodeEditor": "@payloadcms/ui/elements/CodeEditor",
  "@payloadcms/ui#RichText": "@payloadcms/richtext-lexical/client",
}